### ISSUE TITLE
Tumblr Crosspostr doesn't send post formats correctly if a post is created in new Press This

### ISSUE THREAD

**Issue by avcascade** [meitar/tumblr-crosspostr#19]
WordPress 4.2 includes a revamped Press This! bookmarklet, which can expedite the process of reblogging content, whether it be a link, quote, image, or something else. 

Unfortunately, if a post is created using the new bookmarklet, it will not crosspost correctly to Tumblr. 

A post that begins its life in the standard editor will still crosspost with an author's chosen post format, but a post that was started in Press This will not, even if it was finished in the standard editor. Posts begun in Press This apparently always get crossposted with whatever format is the blog's default, regardless of which format the author chose.

*Example*: If an author presses a BBC article and changes the post format from Standard to Link, it will get crossposted to Tumblr as Text, not Link, when published. 

Or (assuming the blog's default format is Link), if an author is blogging a quote from a New York Times story using Press This, and chooses Quote as the post format, it will appear on Tumblr as a Link.

Steps to reproduce using a vanilla WordPress installation (no other plugins except Tumblr Crosspostr):

1. Install WordPress 4.2.2
2. Install Tumblr Crosspostr plugin
3. Connect Tumblr to the WordPress blog (Note: For easier troubleshooting, pick a theme for the Tumblr blog that clearly delineates between different post formats) 
4. Once connected, use Press This (available in Tools) to create a post from some webpage
5. Change the post format to something else, either in Press This, or after saving draft and going into the standard editor to finish
6. Publish and observe results on Tumblr.

**Comment by meitar** [comment]
Was this not an "issue" before WordPress 4.2? The behavior you're describing (the inability to change a post's format once a post is saved, even in draft form) is to be expected from Tumblr, and is even remarked on explicitly in Tumblr Crosspostr's on-screen help. If you're not able to set a Post Format from the WordPress PressThis bookmarklet before the post gets saved (even as a draft), then I'd argue the issue here is sadly with WordPress, not Tumblr Crosspostr.

If enough people are running into this problem it might be useful to provide a workaround in some capacity but that feels a bit scope-creep-y to me. :\

**Comment by avcascade** [comment]
No, there was no issue prior to WordPress 4.2.x. Posts initiated using Press This would crosspost correctly. The problem began after the new Press This shipped. 

New Press This does allow a user to choose the post format from within the bookmarklet. It is also possible to set categories and tags from there. 

Anyone wanting the full editor (i.e. edit HTML) just needs to save the draft and launch into the standard editor to finish up.

**Comment by avcascade** [comment]
Choosing a post format in New Press This looks like this:

![may15-newpressthis-wp](https://cloud.githubusercontent.com/assets/6896314/7596378/0d57df3a-f8a2-11e4-86bf-c0bdb602dbc6.png)

In this screenshot, Standard is selected by default. The default selection will be whichever format the site's owner/admin has chosen in Settings > Writing. 

Though it is possible to change the format, both in Press This *and* in the standard editor prior to publishing, Tumblr Crosspostr will stick with the blog default, overriding the user's choice. The user's choice is still respected when a post is initiated in the standard editor, not Press This.

**Comment by meitar** [comment]
Thanks for the detail here in this bug report, that really helped. Please try the latest development snapshot (commit 6e9f2a10f45ce3981e4a9ddf2b38288bfcb3a848) and let me know if the issue is not yet resolved for you. :)

**Comment by avcascade** [comment]
This patch appears to have resolved the issue.

**Comment by meitar** [comment]
Great, thanks again for the detailed report. :)
