### ISSUE TITLE
Improve Instagrate to WordPress compatability 

### ISSUE THREAD

**Issue by avcascade** [meitar/tumblr-crosspostr#23]
This isn't a bug, but rather a feature request/enhancement.

There exists a rather excellent plugin called [Instagrate to WordPress] (https://wordpress.org/plugins/instagrate-to-wordpress/) that enables clean and reliable crossposting between Instagram and WordPress, similar to what Tumblr Crosspostr does with WordPress and Tumblr, but with a few important differences. Notably, crossposting only works in one direction - posts flow from Instagram to WordPress, but not vice versa. 

What's nice about Instagrate to WordPress is it allows photos posted on Instagram to be automatically added to a WordPress blog. There's no maintenance involved once the plugin is set up. This is good for data ownership. A user who decides to quit Instagram could delete their account, and the photos created through the Instagram app would still be part of that individual's blog archives. 

When Instagrate to WordPress and Tumblr Crosspostr are installed together on a WordPress blog, Tumblr Crosspostr will dutifully crosspost (to Tumblr), the posts that Instagrate sends to WordPress. I have Instagrate configured to post using the Image post format. 

However, these posts aren't being crossposted correctly. They should be sent to Tumblr as image posts, with images included, since that is what they are. But instead, they're being sent as asides. The only part of a crossposted Instagrate post that makes it to Tumblr is the title. 

Instagrate does understand how to cross-post to WordPress intelligently. As mentioned, it can take advantage of post formats, and it uploads the images it copies over into the WordPress media library. Unfortunately, when Tumblr Crosspostr subsequently pushes the same content to Tumblr, it gets scrambled. Is it possible to improve the compatability with Instagrate so that the images Instagrate sends to WordPress can in turn get sent to Tumblr?

**Comment by meitar** [comment]
Depends on how Instagrate saves posts. Tumblr doesn't allow a post created in one format to be changed to another. If Instagrate is creating posts as asides (or "standard" posts) and then changing those posts to Image format, there's nothing Tumblr Crosspostr can do; Tumblr will see those posts as text posts.

From your description, there isn't anything that needs to change in Tumblr Crosspostr to support what you're asking for. Double check Instagrate, instead.

**Comment by avcascade** [comment]
Here's some code from the plugin that appears to be applicable:

			//apply format if not standard
			if ($postformat != 'Standard') {
				set_post_format( $new_post , $postformat);
			}

The more important issue is not which format the post is getting sent as, though... it's the fact that the image isn't coming over with its title.

**Comment by meitar** [comment]
Like I said, images that are set as the WordPress post's "featured image" get crossposted when the post they're associated with is an Image post. You should probably contact the Instagrate developer(s) about this, since Tumblr Crosspostr *does* crosspost images correctly when the post format is set appropriately.
