### ISSUE TITLE
"Post crossposted." When installing a plugin.

### ISSUE THREAD

**Issue by santsys** [meitar/tumblr-crosspostr#27]
I recently installed a plugin and received a "Post crossposted" message.

![image](https://cloud.githubusercontent.com/assets/1380843/14429885/2031fedc-ffb4-11e5-9106-7c3c5d943c11.png)

The link on the message seems to point to the last article that I posted.

This may have been due to a scheduled post going out around the same time... But, not sure the message should have shown there?

**Comment by meitar** [comment]
Was the post that got crossposted supposed to be crossposted?

**Comment by santsys** [comment]
Yes it was.

**Comment by meitar** [comment]
There's no check inside Tumblr Crosspostr to display admin notices only on some pages but not others, so this is just a notice showing you that the post was, indeed, cross-posted. :)
